# -*- coding: utf-8 -*-
"""Colab 구독 최대한 활용하기의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZTiZR88yp5YH4N48CQe97ChEb0NxWlF
"""

#@title 1. ✅ 라이브러리 설치 및 핵심 모듈 불러오기 (최종 수정)

# [수정] unsloth 라이브러리를 GitHub에서 직접 받는 대신, 가장 안정적인 공식 버전을 설치합니다.
!pip install "unsloth[colab-new]"

# %%capture
# 나머지 라이브러리는 동일하게 설치합니다.
!pip install --no-deps "xformers<0.0.26" trl peft accelerate bitsandbytes
!pip install synthetic-data-kit==0.0.3 vllm==0.8.5.post1
!pip install fastapi uvicorn pyngrok nest-asyncio
print("✅ 라이브러리 설치 완료!")

# 설치 후 바로 import하여 모듈을 인식시킵니다.
from unsloth.dataprep import SyntheticDataKit
import time
import os
import nest_asyncio

nest_asyncio.apply()
print("✅ 핵심 모듈 불러오기 완료!")

#@title 2. 📄 학습시킬 PDF 파일 업로드
from google.colab import files
import os

print("파인튜닝에 사용할 PDF 파일을 업로드해주세요.")
uploaded = files.upload()

if not uploaded:
    raise Exception("파일이 업로드되지 않았습니다. 셀을 다시 실행하여 파일을 업로드해주세요.")
else:
    uploaded_filename = next(iter(uploaded))
    print(f"\n✅ 성공적으로 '{uploaded_filename}' 파일이 업로드되었습니다.")

#@title 3. ⚙️ Q&A 데이터 자동 생성 (수정된 코드)
# 업로드한 PDF에서 Q&A 쌍을 자동으로 생성합니다.

# 1. 데이터 생성기 준비
generator = SyntheticDataKit.from_pretrained(
    model_name="unsloth/Llama-3.2-3B-Instruct",
    max_seq_length=4096,
)
generator.prepare_qa_generation(output_folder="data")
print("✅ 데이터 생성기 준비 완료.")

# 2. 파일 이름 설정 및 텍스트 추출
base_name = os.path.splitext(uploaded_filename)[0]

print(f"\n'{uploaded_filename}' 파일의 텍스트를 추출합니다...")
!synthetic-data-kit -c synthetic_data_kit_config.yaml ingest "{uploaded_filename}"

# 3. 텍스트 청크 분할
ingested_text_file = f"data/output/{base_name}.txt"
if not os.path.exists(ingested_text_file):
    raise FileNotFoundError(f"텍스트 파일을 찾을 수 없습니다: {ingested_text_file}")

print(f"\n'{ingested_text_file}' 파일을 청크로 분할합니다...")
chunk_filenames = generator.chunk_data(ingested_text_file)
print(f"✅ 총 {len(chunk_filenames)}개의 데이터 청크 생성 완료.")

# 4. Q&A 쌍 생성
CHUNKS_TO_PROCESS = chunk_filenames[:3]
print(f"\n총 {len(CHUNKS_TO_PROCESS)}개의 청크에 대해 Q&A 생성을 시작합니다...")
for filename in CHUNKS_TO_PROCESS:
    !synthetic-data-kit -c synthetic_data_kit_config.yaml create "{filename}" --num-pairs 25 --type "qa"
    print(f"'{filename}' 처리 완료.")
    time.sleep(1)
print("✅ Q&A 생성 완료.")

# 5. 파인튜닝 형식으로 변환 및 최종 데이터셋 로드
from datasets import Dataset
import pandas as pd

qa_pairs_filenames = [f"data/generated/{base_name}_{i}_qa_pairs.json" for i in range(len(CHUNKS_TO_PROCESS))]
final_filenames = [f"data/final/{base_name}_{i}_qa_pairs_ft.json" for i in range(len(CHUNKS_TO_PROCESS))]

for filename in qa_pairs_filenames:
    if os.path.exists(filename):
        !synthetic-data-kit -c synthetic_data_kit_config.yaml save-as "{filename}" -f ft

all_conversations = [pd.read_json(name) for name in final_filenames if os.path.exists(name)]
if not all_conversations:
    raise Exception("데이터셋을 로드할 수 없습니다. Q&A 데이터가 생성되지 않았습니다.")

dataset = Dataset.from_pandas(pd.concat(all_conversations).reset_index(drop=True))
print(f"\n✅ 최종 데이터셋 준비 완료! 총 {len(dataset)}개의 Q&A 쌍이 로드되었습니다.")

#@title 4. 🔥 모델 파인튜닝 실행
from unsloth import FastLanguageModel
from trl import SFTTrainer, SFTConfig
import torch

# 1. 이전 모델 메모리 정리
generator.cleanup()
torch.cuda.empty_cache()

# 2. 파인튜닝을 위한 모델 로드 (4비트 양자화)
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Llama-3.2-3B-Instruct",
    max_seq_length=4096,
    load_in_4bit=True,
)

# 3. LoRA 설정 적용
model = FastLanguageModel.get_peft_model(
    model, r=16, target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16, lora_dropout=0, bias="none", use_gradient_checkpointing="unsloth",
)

# 4. 데이터셋 포매팅
def formatting_prompts_func(examples):
    texts = [tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False) for convo in examples["messages"]]
    return {"text": texts}
dataset = dataset.map(formatting_prompts_func, batched=True)

# 5. 트레이너 설정 및 훈련 시작
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    args=SFTConfig(
        dataset_text_field="text",
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        max_steps=60, # 테스트를 위해 60으로 설정. 성능을 높이려면 100~200으로 조절
        learning_rate=2e-4,
        logging_steps=5,
        optim="adamw_8bit",
        seed=3407,
        report_to="none",
    ),
)
print("💪 파인튜닝을 시작합니다...")
trainer.train()
print("🎉 파인튜닝 완료!")

#@title 5. 🚀 모델 병합 및 Hugging Face Hub에 업로드 (수정된 코드)
# API 서버에서 사용하기 위해 모델을 병합하고, Hugging Face Hub에 업로드합니다.

# 1. Hugging Face 로그인 및 토큰 준비
from huggingface_hub import HfApi
from getpass import getpass

# Hugging Face 토큰을 입력받습니다.
# 이 셀을 실행하면 나타나는 입력창에 토큰을 붙여넣으세요.
HF_TOKEN = getpass("Hugging Face 'write' 권한 토큰을 붙여넣으세요: ")

# 2. 모델 병합 및 업로드
# ------------------ 중요: 아래 두 변수를 꼭 수정해주세요 ------------------
HF_USERNAME = "jungfgsds"  # ⬅️ 본인의 허깅페이스 사용자 이름을 입력하세요.
HF_MODEL_NAME = "vpp"      # ⬅️ 원하는 모델 이름을 입력하세요.
# --------------------------------------------------------------------

hf_repo_id = f"{HF_USERNAME}/{HF_MODEL_NAME}"

# Hugging Face Hub에 저장소(repository)가 없으면 새로 생성합니다.
api = HfApi(token=HF_TOKEN)
api.create_repo(repo_id=hf_repo_id, exist_ok=True)

print(f"\n모델을 4비트로 병합하여 '{hf_repo_id}'에 업로드합니다...")

# 입력받은 토큰을 직접 전달하여 인증 오류를 해결합니다.
model.push_to_hub_merged(hf_repo_id, tokenizer, save_method="merged_4bit_forced", token=HF_TOKEN)

print(f"✅ 모델 업로드 완료! 이제 '{hf_repo_id}' 이름으로 모델을 사용할 수 있습니다.")

# Commented out IPython magic to ensure Python compatibility.
# #@title 6. 📝 FastAPI 서버 코드 작성 (최종 수정)
# # API 서버 역할을 할 파이썬 코드를 작성합니다.
# %%writefile main.py
# from fastapi import FastAPI
# from pydantic import BaseModel
# from unsloth import FastLanguageModel
# import torch
# import os
# from transformers import BitsAndBytesConfig
# 
# # 1. FastAPI 앱 및 모델 로딩
# app = FastAPI()
# 
# MODEL_REPO_ID = os.environ.get("MODEL_REPO_ID", "unsloth/Llama-3.2-3B-Instruct")
# 
# # CPU 오프로딩을 명시적으로 활성화하는 고급 양자화 설정을 추가합니다.
# quantization_config = BitsAndBytesConfig(
#     load_in_4bit=True,
#     llm_int8_enable_fp32_cpu_offload=True,
# )
# 
# model, tokenizer = FastLanguageModel.from_pretrained(
#     model_name=MODEL_REPO_ID,
#     max_seq_length=4096,
#     quantization_config=quantization_config,
#     device_map="auto",
# )
# print(f"✅ API 서버 모델 로딩 완료: {MODEL_REPO_ID}")
# 
# # 2. 요청/응답 형식 정의
# class PromptRequest(BaseModel):
#     prompt: str
# 
# class PromptResponse(BaseModel):
#     response: str
# 
# # 3. API 엔드포인트 정의
# @app.post("/generate", response_model=PromptResponse)
# async def generate_text(request: PromptRequest):
#     """사용자의 프롬프트를 받아 모델의 답변을 생성합니다."""
#     messages = [{"role": "user", "content": request.prompt}]
# 
#     inputs = tokenizer.apply_chat_template(
#         messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"
#     )
# 
#     outputs = model.generate(input_ids=inputs, max_new_tokens=512)
#     generated_text = tokenizer.batch_decode(outputs[:, inputs.shape[1]:], skip_special_tokens=True)[0]
# 
#     return PromptResponse(response=generated_text)
# 
# # [수정] 문제가 된 주석 부분을 한 줄로 깔끔하게 정리했습니다.
# @app.get("/")
# def health_check():
#     """서버 상태 체크 엔드포인트"""
#     return {"status": "ok"}

#@title 7. 🌐 API 서버 실행 및 외부 접속 URL 생성

# 1. ngrok 설정
# ⬇️ 아래 변수에 새로 발급받은 안전한 ngrok 인증 토큰을 붙여넣으세요.
NGROK_AUTH_TOKEN = "2zYEmPe98r4g2cC6sHoEtsjlEqp_6dhCeK584CchkgbCwrUoP"

# 2. API 서버 실행
from pyngrok import ngrok
import uvicorn
import os

# 환경 변수에 모델 저장소 ID를 설정합니다.
os.environ["MODEL_REPO_ID"] = hf_repo_id

# ngrok 인증 토큰 설정 및 터널 생성
ngrok.set_auth_token(NGROK_AUTH_TOKEN)
public_url = ngrok.connect(8000)
print(f"✅ 외부 접속 가능 URL: {public_url}")
print("🚀 API 서버를 시작합니다... (Colab 셀 실행을 중지하면 서버도 중지됩니다)")

# uvicorn으로 FastAPI 서버 실행
try:
    uvicorn.run("main:app", host="0.0.0.0", port=8000)
except KeyboardInterrupt:
    print("API 서버를 중지합니다.")
    ngrok.kill()

"""후속작업"""

#@title 1. ✅ 라이브러리 설치 및 핵심 모듈 불러오기
!pip install "unsloth[colab-new]"
!pip install --no-deps "xformers<0.0.26" trl peft accelerate bitsandbytes
!pip install fastapi uvicorn pyngrok nest-asyncio
import os
import nest_asyncio
nest_asyncio.apply()
print("✅ 라이브러리 설치 완료!")

#@title 2. 🚀 모델 정보 설정
# 5단계에서 업로드했던 모델 정보를 그대로 입력해주세요.
HF_USERNAME = "jungfgsds"
HF_MODEL_NAME = "vpp"
hf_repo_id = f"{HF_USERNAME}/{HF_MODEL_NAME}"

# 환경 변수에 모델 저장소 ID를 설정합니다. (API 서버가 이 값을 사용합니다)
os.environ["MODEL_REPO_ID"] = hf_repo_id

print(f"✅ API 서버가 사용할 모델: '{hf_repo_id}'")

# Commented out IPython magic to ensure Python compatibility.
# #@title 1. FastAPI 서버 코드 작성
# %%writefile main.py
# from fastapi import FastAPI
# from pydantic import BaseModel
# from unsloth import FastLanguageModel
# import torch
# import os
# from transformers import BitsAndBytesConfig
# 
# app = FastAPI()
# MODEL_REPO_ID = os.environ.get("MODEL_REPO_ID")
# 
# quantization_config = BitsAndBytesConfig(
#     load_in_4bit=True,
#     llm_int8_enable_fp32_cpu_offload=True,
# )
# 
# model, tokenizer = FastLanguageModel.from_pretrained(
#     model_name=MODEL_REPO_ID,
#     max_seq_length=4096,
#     quantization_config=quantization_config,
#     device_map="auto",
# )
# print(f"✅ API 서버 모델 로딩 완료: {MODEL_REPO_ID}")
# 
# class PromptRequest(BaseModel):
#     prompt: str
# class PromptResponse(BaseModel):
#     response: str
# 
# @app.post("/generate", response_model=PromptResponse)
# async def generate_text(request: PromptRequest):
#     messages = [{"role": "user", "content": request.prompt}]
#     inputs = tokenizer.apply_chat_template(
#         messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"
#     )
#     outputs = model.generate(input_ids=inputs, max_new_tokens=512)
#     generated_text = tokenizer.batch_decode(outputs[:, inputs.shape[1]:], skip_special_tokens=True)[0]
#     return PromptResponse(response=generated_text)
# 
# @app.get("/")
# def health_check():
#     """서버 상태 체크 엔드포인트"""
#     return {"status": "ok"}

#@title 2. API 서버 실행
# ------------------ ngrok 토큰만 입력해주세요 ------------------
NGROK_AUTH_TOKEN = "2zYEmPe98r4g2cC6sHoEtsjlEqp_6dhCeK584CchkgbCwrUoP"
# -----------------------------------------------------------

from pyngrok import ngrok
import uvicorn

ngrok.set_auth_token(NGROK_AUTH_TOKEN)
public_url = ngrok.connect(8000)
print(f"✅ 외부 접속 가능 URL: {public_url}")
print("🚀 API 서버를 시작합니다...")

try:
    uvicorn.run("main:app", host="0.0.0.0", port=8000)
except KeyboardInterrupt:
    print("API 서버를 중지합니다.")
    ngrok.kill()